name: muler_dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - scipy
  - matplotlib
  - astropy>=4.0
  - astroquery
  - specutils # Manually install the dev version from GitHub
  - tqdm
  - pandas
  - bokeh>=1.0
  - jupyter
  - ipython
  - seaborn
  - scikit-learn
  - pytest
  - sphinx # for documentation and testing
  - nbsphinx # for documentation and testing
  - numpydoc # for documentation and testing
  - sphinx-automodapi # for documentation and testing
  - black
  - isort
  - tox
  - pip
  - pip:
      - sphinx-material
      - celerite2
