name: muler_dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.8
  - numpy
  - scipy
  - matplotlib
  - astropy<5.0
  - astroquery
  - specutils>=1.2
  - tqdm
  - pandas
  - bokeh
  - jupyter
  - ipython
  - seaborn
  - importlib_resources
  - h5py 
  - pytest
  - sphinx # for documentation and testing
  - nbsphinx # for documentation and testing
  - numpydoc # for documentation and testing
  - sphinx-automodapi # for documentation and testing
  - black
  - isort
  - tox
  - coverage
  - coveralls
  - twine
  - pip
  - pip:
      - sphinx-material
      - celerite2
